alias aliases="cat ~/.bash_aliases"
alias cd="pushd"
alias dc="popd"
alias chx="chmod +x"
alias vim="/usr/local/bin/vim"
alias vi="vim -p"
alias v="vim -p"
alias sv="sudo vim -p"
alias c='clear'                                       # clear screen
alias cp="cp -a"                                      # cp recursive, +perms
alias ebash="v ~/.bashrc"
alias g="git"
alias com="git commit"
alias add="git add"
alias push="git push"
alias pull="git pull"
alias stat="git status"
alias py="python"
alias rb="ruby"
alias head="ssh -A sclaxton@sullivan.opensciencedatacloud.org"
alias ls='ls -a'
alias l.='ls -d .*'
alias .1="cd .."
alias .2="cd ../../"
alias .3="cd ../../../"
alias .4="cd ../../../../"
alias .5="cd ../../../../../"
alias h='history'
alias j='jobs -l'
alias root='sudo -i'
alias wget='wget -c'
alias db="python control.py"
